FROM balenalib/raspberrypi4-64-node:12-build

ENV UDEV=1
ENV DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

RUN apt-get update && apt-get install -y \
    libdbus-1-dev \
    libglib2.0-dev \
    dbus

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm i -g node-gyp
RUN npm install --arch=arm64

COPY tsconfig.json .
COPY src src

CMD ["npm", "start"]
#CMD ["/bin/bash"]